#!/bin/bash -x
UUID=$(uuid)

DATE=`date '+%Y-%m-%d_%H-%M-%S'`
CURRENT_BRANCH=$(git status | head -1 | sed -e 's/^On branch //')
BRANCH=$(git status | head -1 | sed -e 's/^On branch //' | sed -e 's/-.*$//')

gitdir=$(git rev-parse --git-dir)
COMMITMSG=$(head -1 "$gitdir/COMMIT_EDITMSG" | tr -c a-zA-Z0-9 _)

[ -z "$COMMITMSG" ] && {
  echo "No commit message!"
  exit 1
}

ME=$(whoami)
if [ "$CURRENT_BRANCH" = "develop" ] ; then
BR="$ME/$COMMITMSG-$DATE"
else
BR="$BRANCH-$DATE"
fi


git checkout -b "$BR"
git push -u origin "$BR"
